### PR TITLE
Stop the use of deployment object in ansible module

### PR DESCRIPTION
**Pull request by hkariti**
I added a note there and I'm not sure about its phrasing. Thoughts?

@shush @rasienko

### CODE REVIEW

**Comment by dshush** [comment]
👍

**Comment by shaharke** [comment]
@oschreib @hkariti who's deploying to production? Did we deploy the change in the module?

**Comment by hkariti** [comment]
@shaharke not yet deployed anything

**Comment by shaharke** [comment]
@hkariti ok. you own it.

**Comment by rasienko** [comment]
@hkariti I'm not sure what the note means, so we may need to clarify. The note seems to refer to the start event, so I'd move it there. Perhaps we can include an example, as well? Or, let me know if you want to discuss the feature, and I can recommend some text changes.

**Comment by hkariti** [comment]
@rasienko the note is about a second way to use the module. The user can use it either way, but I felt I had to at least mention the possibility of the second one. 

The second way is like this:
for the start event, you'd do:
```
-       local_action: bigpanda token=$TOKEN component={{app_name}} version={{app_version}} hosts={{ansible_hostname}} state=started
        register: deployment
```

and for the finish:
```
-       local_action: bigpanda token={{deployment.token}} component={{deployment.component}} version={{deployment.version}} hosts={{deployment.hosts}} state=finished
```

As you see, it's different for both the start and end event. It's pretty minor, and most ansible users should at least think about this option themselves anyway. I don't want to remove it entirely though, as it's a useful feature for some cases (this is how we use our moduel, for example)

**Comment by rasienko** [comment]
@hkariti I see what you're saying. I think we should include both options in the instructions. Then, include an example of how you'd use the registered event. Something like this...
## Notify BigPanda When a Deployment Starts
Use the BigPanda module in your playbook to send a notification at the start of a deployment.
#### Option 1: Simple (Unregistered Event)
//example code here//
#### Option 2: Advanced (Registered Event)
You can register the event to use the deployment information //reason to do it here//. For example, //something the user might do with it here//.
//example code here//

**Comment by hkariti** [comment]
hm, that's not bad. I'll try that.

**Comment by hkariti** [comment]
@rasienko re-review? Also changed the first section, saw it was outdated.

**Comment by rasienko** [comment]
@hkariti Looking good! For the "deployment end" section, I would move the Note above the options section instead of repeating it. For the note in the "deployment starts" section, do we need to tell them to also change the hosts argument? Also, let's make it more direct. Something like "You must replace the `component`, `version`, and `hosts` arguments with the correct values for your deployment."
(FYI, if you want I can make some minor edits directly in the branch. Just don't want to mess up the pull request, so let me know if it's ok.)

**Comment by hkariti** [comment]
@rasienko sorry for the late response. You can change the branch directly :)

**Comment by hkariti** [comment]
also, they don't need to change the host argument

**Comment by rasienko** [comment]
@hkariti made some minor edits for your review. let me know how it looks. thanks!

**Comment by hkariti** [comment]
👍

**Pull request merged**
