### PR TITLE
New Appdynamics web hook integration tutorial

### PR DESCRIPTION
**Pull request by erikzaadi**
@rasienko have a looksie!

@dshush u too

### CODE REVIEW

**Comment by erikzaadi** [comment]
See visual at https://stg-a.bigpanda.io/#/app/integrations/appdynamicsapi/instructions/appdynamicsapi-webhooks

**Comment by shaharke** [comment]
@erikzaadi for any new health violation check they'll have to configure BigPanda manually right?

**Comment by erikzaadi** [comment]
@shaharke Only add the action, yes. The HTTP Template and action are only defined once

**Comment by shaharke** [comment]
Cool

**Comment by erikzaadi** [comment]
@rasienko Benga already gave me some feedback, I hope to add the fixes here before your hours so that you won't need to review non relevant code

**Comment by erikzaadi** [comment]
Done!

**Comment by dshush** [comment]
They need to create a policy for each application like they do in the custom action? in the custom action tutorial it is mentioned in the last part, we need it here too?

Also - maybe it will be helpful to add from which version AppDynamics supports webhook somewhere? (if you add it already and I've missed it - sorry..)

**Comment by rasienko** [comment]
Hi Erik & Shush,

Thanks for sending! Here are a few updates on the documentation.

1. I took a look at the new tutorial and I made several edits in Github.
Please review them and let me know if changes are required.

2. I updated the existing tutorial in Github. Please review my edits and
let me know if changes are required. I also had several questions about the
Compatibility section.

   - It says to contact AppDynamics for help with steps 2 - 4, but I think
   the steps should be 4 - 6. Is that correct?
   - Is the windows controller another version of AppDynamics, or do all
   on-premise deployments use the windows controller?
   - I edited this section based on what I think the answers to these
   questions are. Please review my changes and let me know if I've
   misinterpreted anything.


3. We also need a few more documentation changes before we go live with the
feature. Can you update these items?

   - We will need to update the Available Integrations page in the Docs to
   reflect the new integration:
   https://www.bigpanda.io/docs/display/DD/.Available+Integrations+vNext
      - Make sure the Working Version is set to Next before editing. If you
      follow the link, the version should be set automatically.
      - You can edit or make comments as you'd like. We'll publish the
      updates when everything is ready, and the comments will remain internal.
      - I created a stub article for the release announcement here:
   https://bigpandaio.zendesk.com/hc/en-us/articles/206312126
   - Be sure the *Draft* check box remains selected.
      - Please add/edit content directly. Refrain from using the comments,
      as I'm not aware of a way to use internal comments for Zendesk.
   - Please also take a look at this page and confirm that it is still
   accurate or make updates, if necessary:
   https://www.bigpanda.io/docs/display/DD/Uninstalling+the+BigPanda+Custom+Action+from+AppDynamics
      - Again, be sure the Working Version is set to Next before editing.
      - If you edit this page, the system should notify you that you are
      creating a page in the Next version. That is what you want to do for this
      page should it need updating.

Let me know when these items are ready for review, and let me know if
there's anything else to edit or write. I'm available to meet if we need to
chat about anything, as well.

Thanks,
-Rachel

**Comment by erikzaadi** [comment]
@rasienko the edits looks great, did some markdown tweaks (new line is needed before bullet lists etc).

https://www.bigpanda.io/docs/display/BD/Uninstalling+the+BigPanda+Custom+Action+from+AppDynamics seems legit, still relevant for old integration.
Adding the others as tasks.

**Pull request merged**
