### PR TITLE
SolarWinds tutorial updates BUG-374

### PR DESCRIPTION
**Pull request by rasienko**
@erikzaadi please review and merge. Let me know if you need any additional info. Thanks!

### CODE REVIEW

**Comment by erikzaadi** [comment]
Looks fine:

image


https://odzomg-a.bigpanda.io/#/app/integrations/solarwinds.mermer_nginx/instructions/solarwinds

**Comment by erikzaadi** [comment]
@rasienko please validate in the url I sent, if it's ok, I'll merge. looks great from my point of view

**Comment by rasienko** [comment]
@erikzaadi tutorial looks great! Can you please merge & push to prod? Also note that there's an update for the in-product FAQs in the bug report (I think that text is in frontier so I didn't open a pull request). Let me know if you have questions. Thanks!

**Comment by rasienko** [comment]
@erikzaadi what's the status of this PR? Do you have what you need to merge and deploy?

**Comment by erikzaadi** [comment]
@rasienko Yes! Will merger today and update you in slack

**Pull request merged**
