### PR TITLE
Aymohammed deployments 1

### PR DESCRIPTION
**Pull request by aymohammed**
@rasienko this is what I've changed so far. Thoughts?

### CODE REVIEW

**Comment by rasienko** [comment]
Looks really great! Some feedback…
* The text in the first note sounds a bit redundant. I think you can remove the first sentence or else combine them and shorten. 
* Use bold for the **Note:** font (two asterisks).
* Let’s add a link somewhere to the docs for the Deployments API so they can get more info (like we did for Alerts).

**Comment by aymohammed** [comment]
Ready for your review @erikzaadi! If it checks out, can you push it to staging? 
Thanks!

**Comment by erikzaadi** [comment]
@aymohammed Deployed to staging 3

**Comment by aymohammed** [comment]
Final changes have been made. All set to go after your review @erikzaadi. Thank you!!!

**Comment by rasienko** [comment]
@erikzaadi same here..is this merged/close?

**Pull request merged**
