### PR TITLE
Feature/migrate alertapi parent

### PR DESCRIPTION
**Pull request by yardenmintz**
@erikzaadi @shaharke please review

### CODE REVIEW

**Comment by shaharke** [comment]
:+1:

**Comment by rasienko** [comment]
@erikzaadi just checking that this won't conflict with the edits from @aymohammed. Let us know if we need to make any changes. Thanks!

**Comment by erikzaadi** [comment]
@rasienko perhaps, but git should be able to resolve that, if not I'll fix it.

**Comment by rasienko** [comment]
cool, thanks @erikzaadi!

**Pull request merged**
